### ISSUE TITLE
如何发送分享链接到多个群里面

### ISSUE THREAD

**Issue by lihuacai168** [Mocha-L/WechatPCAPI#11]
## 想实现一个功能：

- 1.先把分享链接发送到`文件传输助手`
- 2.然后接收到的功能自动转发到预先定义好的群

## 不知道的接口：
- 1.如何转发分享链接到群里面
- 2.发送消息到群里面的接口 
- 3.根据群名搜索对应的群id

**Comment by Mocha-L** [comment]
1. 发链接卡片到群里面 请参照test.py
2. 发送消息到群，请参照test.py
3. on_message会给你整个好友关系表，里面你自己找到群名和群id的关系啊
