### ISSUE TITLE
掃到很多毒...

### ISSUE THREAD

**Issue by twlinxi** [Mocha-L/WechatPCAPI#12]
https://www.virustotal.com/gui/file/5676051ddf3f4dd5337a7c4f39438385d4c4234d2635671c22b3346223d2e556/detection

**Comment by Mocha-L** [comment]
你在虚拟机运行一下
本身hook和远线程就会被报毒的


 
---原始邮件---
发件人: "twlinxi"<notifications@github.com&gt;
发送时间: 2020年2月20日 22:33:43
收件人: "Mocha-L/WechatPCAPI"<WechatPCAPI@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Mocha-L/WechatPCAPI] 掃到很多毒... (#12)



https://www.virustotal.com/gui/file/5676051ddf3f4dd5337a7c4f39438385d4c4234d2635671c22b3346223d2e556/detection
