### ISSUE TITLE
非文本消息怎么解析

### ISSUE THREAD

**Issue by chunkin-dev** [Mocha-L/WechatPCAPI#14]
有计划吗，比如像Itchat一样直接把msg给解析给封装起来？

**Comment by Mocha-L** [comment]
新版本新增了图片语音文件视频的自动下载，你可以看看应该可以解决你的问题

**Comment by chunkin-dev** [comment]
只有收费版能用吗，test.py里代码没体现？比如分享、名片这些都能处理吗？

**Comment by Mocha-L** [comment]
test里是有的 send_link_card就是
支持分享链接的发送 不支持好友名片
