### ISSUE TITLE
免费版无法使用

### ISSUE THREAD

**Issue by zaijuejingduli** [Mocha-L/WechatPCAPI#15]
免费版文件好像和收费的混用了，不能直接运行，而且在修改报错的文件名之后也无法连接上微信客户端（出现INFO:root:Accept new connection from 127.0.0.1:4755就没了，不显示登陆成功

**Comment by zaijuejingduli** [comment]
当然如果是已经把免费版取消了的话，就当我没说吧。。。

**Comment by Mocha-L** [comment]
可以用，jusr try again.
