### ISSUE TITLE
send_link_card中target_url过长出现crash

### ISSUE THREAD

**Issue by feijian123456** [Mocha-L/WechatPCAPI#18]
调用send_link_card()方法分享微信公众号链接时WechatPCHelper.dll或报错退出，分享示例链接时无异常，测试了一下，好像是比较长的链接作为target_url就会报错退出，出现如下错误信息：
![1](https://user-images.githubusercontent.com/9881674/77864988-97f30580-725e-11ea-8225-4b3fc0709f16.png)

**Comment by Mocha-L** [comment]
过长找一下转短链接的API 转换一下吧 @feijian123456
