### ISSUE TITLE
关于回调函数

### ISSUE THREAD

**Issue by mortimer-cra** [Mocha-L/WechatPCAPI#2]
请问如何在收到消息的回调函数中调用发送消息接口

**Comment by Mocha-L** [comment]
暂时没有提供这个功能，因为不建议在回调函数里做过多的事情，这样会阻挡后续的接收数据。
建议是在回调函数将数据自行保存到队列或其他数据结构后直接返回，再有自己的其他处理业务进行数据分析和触发操作。

**Comment by Mocha-L** [comment]
@mortimer-cra

**Comment by mortimer-cra** [comment]
嗯嗯 但是回调函数中会把自己发给别人的消息也会发送回来 完全无法分辨接受的消息是自己发给别人的还是别人发给自己的 因为from_wxid都是一样的

**Comment by mortimer-cra** [comment]
有没有办法能让自己发给其他人的消息不走接受消息的函数呢？

**Comment by Mocha-L** [comment]
@mortimer-cra 多谢你的提醒
这个是我设计的疏漏，我最近会把他修复掉，改好了@你。

> 我计划在每条消息中新增一个标志，是发出的还是收到的。

**Comment by mortimer-cra** [comment]
好的 为你加油大佬

**Comment by Mocha-L** [comment]
我改好再关闭吧

**Comment by Mocha-L** [comment]
@mortimer-cra 更新新增“消息是发出的还是接收的”字段说明 ，新增未读消息数量消息类型 可用于协助判断消息送达等
你更新一下试试，要是OK了的话再close吧。多谢。

**Comment by mortimer-cra** [comment]
测试了 没有问题。请你喝杯咖啡，期待更新自动通过好友申请功能，支持你！
