### ISSUE TITLE
send_file 

### ISSUE THREAD

**Issue by guyujun** [Mocha-L/WechatPCAPI#23]
File "WechatPCAPI\WechatPCAPI.py", line 212, in WechatPCAPI.WechatPCAPI.send_file
TypeError: send_file() takes exactly 3 positional arguments (2 given)

**Comment by guyujun** [comment]
wx_inst.send_file(to_user='24003276891@chatroom', file_abspath=msgcontent) api文档中只有2个变量

**Comment by Mocha-L** [comment]
到底是几个参数呢
其中有一个参数是self啊 你用wx_inst调用就相当于带入了self 那你还需要传入对方id和文件绝对路径两个参数
