### ISSUE TITLE
ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by CatciSurn** [Mocha-L/WechatPCAPI#24]
# code
```
# test.py 3.7.6
import logging
from queue import Queue
from WechatPCAPI import WechatPCAPI

listen_queue = Queue()
def listen(msg):
    listen_queue.put(msg)

logging.basicConfig(level=logging.INFO)
pc_api = WechatPCAPI(on_message=listen, log=logging)
pc_api.start_wechat(block=True)
```
在初次运行此代码时出现该问题
虽然我知道这不是一个bug，可是我想请问一下该如何解决
搜索引擎搜索到的方法无效果
# 目录结构
-----------lib
|    |--open_wechat_multi.exe
|    |--WechatPCHelper.dll
|-WechatPCAPI.pyd
|-test.py

**Comment by CatciSurn** [comment]
from WechatPCAPI import WechatPCAPI
ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。

**Comment by CatciSurn** [comment]
问题解决了
当我尝试卸载电脑内的2.7时，程序正常运行，但我不知道为什么这样

**Comment by Mocha-L** [comment]
是这样子 你可能没好好看FAQ文件和readme
这个仅支持python37 64位 因为这个pyd文件是我用python37打包的
所以你用的python2.7会不能用

**Comment by CatciSurn** [comment]
是这样的，我是拿3.7.4运行的，但是我的电脑同时装了2.7版本的python，我没料到它们会互相影响。
但不管怎么说，问题解决了，由衷感谢你们制作的API
