### ISSUE TITLE
INFO:root:wechat start failed.

### ISSUE THREAD

**Issue by renoyuan** [Mocha-L/WechatPCAPI#28]
python 版本3.7 微信版本 2.7.1.82 使用免费版 一直运行程序
INFO:root:thread_recv_data start.
INFO:root:thread_send_data start.
INFO:root:wechat start failed.
INFO:root:thread_handle_message_from_wx start.

**Comment by renoyuan** [comment]
请问是什么原因呢

**Comment by sevencj** [comment]
扫码登录啊

**Comment by renoyuan** [comment]
已经是登录状态的

**Comment by sevencj** [comment]
wechat start failed 启动失败

**Comment by renoyuan** [comment]
while not wx_inst.get_myself(): 
这里的状态好像一直确认不了，请问是对微信安装目录有要求吗？还是其他原因

**Comment by sevencj** [comment]
要把原来的微信删了

**Comment by sevencj** [comment]
回调函数那里你琢磨一下

**Comment by renoyuan** [comment]
哦哦，可以了，大佬是直接改了微信源码吗？

**Comment by WalkOnMars** [comment]
> 哦哦，可以了，大佬是直接改了微信源码吗？

你能接受到微信消息并打印在控制台吗，我扫码登陆成功后，也一直卡在 while not wx_inst.get_myself() 里面

**Comment by Mocha-L** [comment]
这种问题也建议看一下FAQ，大都能解决。
原因很可能是因为，杀软删掉了exe文件或者dll文件。（上述两个问题的现象都是）
杀软给个白名单就好了
