### ISSUE TITLE
微信图片如何解密解密

### ISSUE THREAD

**Issue by miniluckyant** [Mocha-L/WechatPCAPI#32]
'msg':
 '<?xml version="1.0"?>
<msg>
<img aeskey="" encryver="0" cdnthumbaeskey="****" cdnthumburl="*****" cdnthumblength="6909" cdnthumbheight="120" cdnthumbwidth="96" cdnmidheight="0" cdnmidwidth="0" cdnhdheight="0" cdnhdwidth="0" cdnmidimgurl="*****" length="84378" md5="*****8" />
</msg>'
你好，大佬！微信收到的图片消息，如何解密获取到微信图片的url呢？

**Comment by Mocha-L** [comment]
试用版有个自动保存图片文件等的功能可以下载下来保存并告诉你绝对路径
至于你说用xml下载图片我也不清楚，我也是通过hook微信客户端，借助微信自身下载的资源~

**Comment by miniluckyant** [comment]
哦哦，了解了。
免费版里，收到图片消息时，msg中是一段xml信息，百度上也没搜到明确的说法。以为大佬会清楚点，哈哈哈。
咱继续研究研究。
