### ISSUE TITLE
有一个使用过程中的问题咨询一下大兄弟

### ISSUE THREAD

**Issue by smartbrainisme** [Mocha-L/WechatPCAPI#33]
你好，在src目录的工程中调用get_friends()在控制台报错
AttributeError: 'WechatPCAPI' object has no attribute 'get_friends'
谢谢您的解答

**Comment by Mocha-L** [comment]
你这个应该是免费版吧，src目录是免费版。
这个版本的更新好友信息的函数名是：update_frinds。
你可以看下test.py更清楚~
