### ISSUE TITLE
有木马病毒

### ISSUE THREAD

**Issue by liangyf26** [Mocha-L/WechatPCAPI#4]
lib目录下的文件有 恶意软件(HEUR/QVM10.2.D911.Malware.Gen) 和 木马程序(Trojan.Generic)

**Comment by Mocha-L** [comment]
是易语言程序编写的dll报毒了，这是个钩子模块，项目的实现就是给微信挂钩子实现的功能，看你怎么理解毒了。
实在不放心的话，还是别用了。
